apiVersion: v1
kind: Pod
metadata:
  name: yotta-load-test
  namespace: user1
spec:
  restartPolicy: Never
  containers:
  - name: load-generator
    image: busybox
    command: ["/bin/sh"]
    args:
      - -c
      - |
        while true; do
          wget -q -O- http://yotta-web;
        done
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 300m
        memory: 128Mi

